# Generated by Django 4.2.7 on 2025-11-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
